# Generated by Django 5.1.6 on 2025-02-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('routine_name', models.CharField(default='Morning Routine', max_length=255)),
                ('description', models.CharField(default='Morning Routine Description', max_length=255)),
                ('start_date', models.TimeField()),
                ('end_date', models.TimeField()),
                ('programs', models.ManyToManyField(related_name='program_routines', to='programs.skinprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('instruction_name', models.CharField(default='Instruction Name', max_length=255)),
                ('instruction_description', models.CharField(default='Instruction Description', max_length=255)),
                ('instruction_number', models.IntegerField(null=True)),
                ('routines', models.ManyToManyField(related_name='routine_instructions', to='routines.skinroutine')),
            ],
        ),
    ]
