# Generated by Django 5.1.6 on 2025-02-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructions',
            name='image',
            field=models.URLField(default='https://i.pinimg.com/474x/47/16/0b/47160bc6ba111b50084c244853a03744.jpg'),
        ),
        migrations.AlterField(
            model_name='skinroutine',
            name='image',
            field=models.URLField(default='https://i.pinimg.com/474x/47/16/0b/47160bc6ba111b50084c244853a03744.jpg'),
        ),
    ]
