# Generated by Django 5.1.5 on 2025-01-29 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinationSkinProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Balanced Skin Care Routine', max_length=255)),
                ('description', models.TextField(default='A 2-week program to balance hydration and oil production for combination skin.')),
                ('duration', models.CharField(default='2 weeks', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DrySkinProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hydration Boost Program', max_length=255)),
                ('description', models.TextField(default='A 4-week program designed to restore moisture levels and improve the skin barrier for dry skin.')),
                ('duration', models.CharField(default='4 weeks', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NormalSkinProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Daily Skin Maintenance Routine', max_length=255)),
                ('description', models.TextField(default='A 2-week program for maintaining the health and radiance of normal skin.')),
                ('duration', models.CharField(default='2 weeks', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OilySkinProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Oil Control Regimen', max_length=255)),
                ('description', models.TextField(default='A 3-week program focusing on reducing excess sebum and preventing clogged pores for oily skin.')),
                ('duration', models.CharField(default='3 weeks', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SensitiveSkinProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gentle Skin Program', max_length=255)),
                ('description', models.TextField(default='A 1-month program designed to soothe and strengthen sensitive skin.')),
                ('duration', models.CharField(default='1 month', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_program', models.CharField(default='None', max_length=255)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_program', to='user_profiles.userprofile')),
            ],
        ),
    ]
