# Generated by Django 5.1.5 on 2025-01-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CombinationSkinProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Balanced Skin Care Routine', max_length=255)),
                ('description', models.TextField(default='A 2-week program to balance hydration and oil production for combination skin.')),
                ('duration', models.CharField(default='2 weeks', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DrySkinProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hydration Boost Program', max_length=255)),
                ('description', models.TextField(default='A 4-week program designed to restore moisture levels and improve the skin barrier for dry skin.')),
                ('duration', models.CharField(default='4 weeks', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NormalSkinProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Daily Skin Maintenance Routine', max_length=255)),
                ('description', models.TextField(default='A 2-week program for maintaining the health and radiance of normal skin.')),
                ('duration', models.CharField(default='2 weeks', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OilySkinProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Oil Control Regimen', max_length=255)),
                ('description', models.TextField(default='A 3-week program focusing on reducing excess sebum and preventing clogged pores for oily skin.')),
                ('duration', models.CharField(default='3 weeks', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SensitiveSkinProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gentle Skin Program', max_length=255)),
                ('description', models.TextField(default='A 1-month program designed to soothe and strengthen sensitive skin.')),
                ('duration', models.CharField(default='1 month', max_length=50)),
            ],
        ),
    ]
