# Generated by Django 5.1.5 on 2025-01-30 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hydration Boost Program', max_length=255)),
                ('description', models.TextField(default='A 4-week program designed to restore moisture levels and improve the skin barrier for dry skin.')),
                ('duration', models.CharField(default='4 weeks', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=49.99, max_digits=6)),
                ('image', models.ImageField(upload_to='images/')),
                ('skin_type', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_program', models.CharField(default='None', max_length=255)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_program', to='user_profiles.userprofile')),
            ],
        ),
    ]
