# Generated by Django 5.1.5 on 2025-01-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentprogram',
            name='current_program',
        ),
        migrations.AddField(
            model_name='currentprogram',
            name='current_program',
            field=models.ManyToManyField(related_name='current_programs', to='programs.skinprogram'),
        ),
    ]
