# Generated by Django 5.1.5 on 2025-01-28 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkinAssessmentResults',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('skin_type', models.CharField(default='Default Skin Type', max_length=500)),
                ('recommended_products', models.JSONField(blank=True, default=list)),
                ('recommended_programs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='AssessmentOwner', to='user_profiles.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
