# Generated by Django 5.0.7 on 2025-01-27 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(blank=True, default='.', null=True, upload_to='images/')),
                ('user_name', models.CharField(default='no-username', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
